embedding_model: "<EMBEDDING_MODEL>"
db_host: "<DB_HOST>"
db_user: <DB_USER>
db_password: "<DB_PASSWORD>"
collection_name: "<COLLECTION_NAME>"
marketing_doc : "<MARKETING_DOC>"
clinical_doc: "<CLINICAL_DOC>"